import * as React from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';

import styles from '../styles/Home.module.css';

export default function Home() {
  const { push } = useRouter();

  React.useEffect(() => {
    const token = localStorage.getItem('token');

    if (!token) {
      push('/login');
    }
  }, [push]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Todo-App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
