import { Fab } from '@mui/material';
import { Add as IconAdd } from '@mui/icons-material';
import * as React from 'react';
import Head from 'next/head';

import style from '../styles/Home.module.css';
import { TodoListContainer } from '../containers';
import { CreateTodoFormDialogContainer } from '../containers';

export default function Home() {
  const [open, setOpen] = React.useState(false);

  const onOpen = React.useCallback(() => {
    setOpen(true);
  }, []);

  const onClose = React.useCallback(() => {
    setOpen(false);
  }, []);

  return (
    <div className={style.container}>
      <Head>
        <title>{'Todo - App'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TodoListContainer />

      <Fab color="primary" aria-label="add" style={styles.fab} onClick={onOpen}>
        <IconAdd />
      </Fab>

      <CreateTodoFormDialogContainer open={open} onClose={onClose} />
    </div>
  );
}

const styles = {
  fab: {
    position: 'absolute',
    right: 16,
    bottom: 16
  }
};
