import * as React from 'react';
import Head from 'next/head';

import styles from '../styles/Home.module.css';
import { TodoListContainer } from '../containers';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Todo-App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TodoListContainer />
    </div>
  );
}
